/*
 TalentCalc_dede.js version 297 (01.08.2009)
*/
cO(LANG, {
	tc_rank: "Rang $1/$2",
	tc_tier: "Benotigt $1 Punkte bei $2-Talenten",
	tc_prereq: "Benotigt $1 Punkt in $2",
	tc_prereqpl: "Benotigt $1 Punkte in $2",
	tc_learn: "Zum Erlernen hier klicken",
	tc_unlearn: "Rechtsklick zum Verlernen",
	tc_unlearn2: "Shift-Klick zum Verlernen",
	tc_nextrank: "Nachster Rang:",
	tc_inccap: "Klicken, um auf 80 zu erhohen",
	tc_deccap: "Klicken, um auf 70 zu verringern",
	tc_addbon: "Klicken, um 4 Extrapunkte durch<br />das Talent 'Herr der Tiere' hinzuzufugen",
	tc_rembon: "Klicken, um die Extrapunkte<br />durch 'Herr der Tiere' zu entfernen",
	tc_point: "Punkt",
	tc_points: "Punkte",
	tc_none: "Keine",
	tc_printh: "Stufe $1 $2",
	tc_link: "Link",
	tc_resetall: "Alle loschen",
	tc_lock: "Sperren",
	tc_unlock: "Entsperren",
	tc_reset: "loschen",
	tc_ptsleft: "Verbleibende Punkte: ",
	tc_ptsspent: "Vergebene Punkte: ",
	tc_reqlevel: "Benotigte Stufe: ",
	tc_levelcap: "Stufenbeschrankung: ",
	tc_bonuspts: "Bonuspunkte: ",
	tc_help: "Hilfe",
	tc_import: "Importieren",
	tc_summary: "Zusammenfassung",
	tc_restore: "Wiederherstellen",
	tc_export: "Exportieren",
	tc_glyphs: "Glyphen",
	tc_empty: "Leer",
	tc_majgly: "Erhebliche Glyphe",
	tc_mingly: "Geringe Glyphe",
	tc_addgly: "Zum Einschreiben eurer Zauber rechtsklicken",
	tc_remgly: "Zum Entfernen rechtsklicken",
	tc_remgly2: "Zum Entfernen Shift-Klick",
	tc_nonegly: "Keine",
	alert_invalidurl: "Ungultige URL.",
	alert_chooseclass: "Bitte wahlt zunachst eine Klasse aus.",
	alert_choosefamily: "Bitte wahlt zunachst eine Tierart aus.",
	alert_buildempty: "Ihr habt noch keine Talentpunkte verteilt.",
	prompt_importwh: "Bitte gebt die URL einer Talentverteilung ein, die mit dem Talentrechner von Wowhead erstellt wurde:",
	prompt_importblizz: "Bitte gebt die URL einer Talentverteilung ein, die mit dem Talentrechner von Blizzard erstellt wurde:"
});